# Notebook 1 : Découverte de Pandas

In [ ]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [15]:
import pandas as pd
df = pd.read_csv("../data/iris.csv")
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

2. Sélectionner les variables `PetalWidth` et `Species`.

In [16]:
print(df[["PetalWidth", "Species"]])

     PetalWidth    Species
0           0.2     setosa
1           0.2     setosa
2           0.2     setosa
3           0.2     setosa
4           0.2     setosa
..          ...        ...
145         2.3  virginica
146         1.9  virginica
147         2.0  virginica
148         2.3  virginica
149         1.8  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [17]:
print(df[(df["Species"] == "virginica") | (df["Species"] == "setosa") ])

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [50]:
# df[df["Species"] == "setosa"].count()
len(df[df["Species"] == "setosa"])

50

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [ ]:
df[df["Species"] == "versicolor"]["PetalWidth"].mean()

np.float64(1.3259999999999998)

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [55]:
df["Sumwidth"] = df.PetalWidth + df.SepalWidth

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [57]:
df[["SepalLength"]].groupby(df.Species).agg(["mean", "var"])

           SepalLength
                  mean       var
Species
setosa           5.006  0.124249
versicolor       5.936  0.266433
virginica        6.588  0.404343

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

In [59]:
moy = df[["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]].groupby(df.Species).mean()
#transformation format long
print(
    moy.reset_index()
    .melt(id_vars = ["Species"], value_name = "measure")
)

       Species     variable  measure
0       setosa  SepalLength    5.006
1   versicolor  SepalLength    5.936
2    virginica  SepalLength    6.588
3       setosa   SepalWidth    3.428
4   versicolor   SepalWidth    2.770
5    virginica   SepalWidth    2.974
6       setosa  PetalLength    1.462
7   versicolor  PetalLength    4.260
8    virginica  PetalLength    5.552
9       setosa   PetalWidth    0.246
10  versicolor   PetalWidth    1.326
11   virginica   PetalWidth    2.026

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

6. Sélectionner les vols à destination de `JFK`.

7. Compter le nombre de vols à destination de `JFK`.

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.