# Notebook 2 : Pandas avancé

In [68]:
import pandas as pd

## Tennis

Nous considérons les données des résultats des matchs de tennis masculin des tournois de Roland Garros et Wimbledon en 2013. La liste des variables et leur signification se trouvent sur [cette page](https://archive.ics.uci.edu/dataset/300/tennis+major+tournament+match+statistics) dans la section *Additional Variable Information*.

1. Commencer par charger le jeu de données relatif au tournoi de Roland Garros dans un dataframe `rg` à partir du fichier `rolandgarros2013.csv`.

In [69]:
tennis = pd.read_csv("../data/rolandgarros2013.csv")
tennis.head(5)

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,7,7,14,18,88,6,6,6.0,NaN,NaN
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,1,16,22,25,106,3,3,5.0,NaN,NaN
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,10,18,19,27,139,3,3,6.0,6.0,3.0
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,4,13,33,43,149,6,3,7.0,6.0,NaN
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,4,7,12,13,93,6,6,6.0,NaN,NaN

2. Afficher les noms des demi-finalistes.

In [70]:
tennis[tennis["Round"] == 6].filter(like="Player")

            Player1             Player2
122    David Ferrer  Jo-Wilfried Tsonga
123  Novak Djokovic        Rafael Nadal

3. Calculer le nombre moyen d'aces par match dans le tournoi.

In [74]:
tennis["ACE_tot"]= tennis["ACE.1"] + tennis["ACE.2"] 
tennis["ACE_tot"].mean()

np.float64(12.688)

In [75]:
tennis.assign(ACE_tot=tennis["ACE.1"] + tennis["ACE.2"])["ACE_tot"].mean()

np.float64(12.688)

4. Combien y a-t-il eu d'aces par match en moyenne à chaque niveau du tournoi ?

In [76]:
(
    tennis
    .groupby(tennis.Round)
    .ACE_tot.agg(["mean"])
)

            mean
Round
1      13.476190
2      13.193548
3      12.562500
4       9.125000
5       7.000000
6      10.000000
7       6.000000

In [16]:
tennis.groupby("Round")["ACE_tot"].mean().to_frame()

         ACE_tot
Round
1      13.476190
2      13.193548
3      12.562500
4       9.125000
5       7.000000
6      10.000000
7       6.000000

5. Filtrer les matchs pour lesquels au moins une des variables `DBF.1` et `DBF.2` est manquante.

In [11]:
tennis[tennis["DBF.1"].isna() | tennis["DBF.2"].isna()]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,ACE_tot
56,Simone Bolelli,Yen-Hsun Lu,1,0,0,3,63,33,37,12,...,11,4,6,78,6,6,2.0,NaN,NaN,8
63,Somdev Devvarman,Roger Federer,2,0,0,3,61,19,39,16,...,14,19,30,88,6,6,6.0,NaN,NaN,5

6. Remplacer les valeurs manquantes de `DBF.1` par zéro avec la méthode `loc`.

In [30]:
# Attention, vue partielle du df auqeul on change une valeur, ne fonctionne pas
# tennis[tennis["DBF.1"].isna(), "DBF.1"] = 0

# avec une copie indépendante ( données initales non podifiées)
# test = tennis[tennis["DBF.1"].isna()].copy()
# test["DBF.1"] = 0
# test[["Player1", "Player2", "DBF.1", "DBF.2"]]

# Bonne méthode pour modifier les données initiales
tennis.loc[tennis["DBF.1"].isna(), "DBF.1"] = 0

In [29]:
tennis[tennis["DBF.1"].isna()]

Empty DataFrame
Columns: [Player1, Player2, Round, Result, FNL.1, FNL.2, FSP.1, FSW.1, SSP.1, SSW.1, ACE.1, DBF.1, WNR.1, UFE.1, BPC.1, BPW.1, NPA.1, NPW.1, TPW.1, ST1.1, ST2.1, ST3.1, ST4.1, ST5.1, FSP.2, FSW.2, SSP.2, SSW.2, ACE.2, DBF.2, WNR.2, UFE.2, BPC.2, BPW.2, NPA.2, NPW.2, TPW.2, ST1.2, ST2.2, ST3.2, ST4.2, ST5.2, ACE_tot]
Index: []

[0 rows x 43 columns]

7. Remplacer les valeurs manquantes de `DBF.2` par zéro avec la méthode `fillna`.

In [31]:
tennis["DBF.2"].fillna(0, inplace=True)

/tmp/ipykernel_8130/3648862645.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  tennis["DBF.2"].fillna(0, inplace=True)

In [32]:
tennis[tennis["DBF.2"].isna()]

Empty DataFrame
Columns: [Player1, Player2, Round, Result, FNL.1, FNL.2, FSP.1, FSW.1, SSP.1, SSW.1, ACE.1, DBF.1, WNR.1, UFE.1, BPC.1, BPW.1, NPA.1, NPW.1, TPW.1, ST1.1, ST2.1, ST3.1, ST4.1, ST5.1, FSP.2, FSW.2, SSP.2, SSW.2, ACE.2, DBF.2, WNR.2, UFE.2, BPC.2, BPW.2, NPA.2, NPW.2, TPW.2, ST1.2, ST2.2, ST3.2, ST4.2, ST5.2, ACE_tot]
Index: []

[0 rows x 43 columns]

8. Extraire la liste des participants à partir des colonnes `Player1` et `Player2`. Une façon de faire consiste à utiliser `concat` et la méthode `drop_duplicates` pour obtenir le résultat sous la forme d'une série et de la convertir en dataframe avec la méthode `to_frame`.

In [ ]:

rg_joueur = 
(
    pd.concat([tennis["Player1"], tennis["Player2"]])
    .drop_duplicates()   # récupérer les valeurs uniques
    .to_frame(name="Joueur")  # convertit série en dataframe
    .reset_index(drop=True)  # reset index vec drop = false : ramène la colonne en index en colonne, # reset index avec drop = true : supprime lancienne colonne d'index
)
rg_joueur

                  Joueur
0    Pablo Carreno-Busta
1       Somdev Devvarman
2           Tobias Kamke
3       Julien Benneteau
4            Lukas Lacko
..                   ...
122          Yen-Hsun Lu
123      Grigor Dimitrov
124          Guido Pella
125         David Goffin
126     Janko Tipsarevic

[127 rows x 1 columns]

9. Écrire une fonction `n_match` qui prend une chaîne de caractères `joueur` en entrée et retourne le nombre de matchs disputés par le joueur.

In [54]:
def n_match(joueur):
    return len(tennis.loc[(tennis["Player1"] == joueur) | (tennis["Player2"] == joueur)])

rg_joueur["n_match"]=rg_joueur["Joueur"].apply(n_match)
rg_joueur

                  Joueur  n_match
0    Pablo Carreno-Busta        1
1       Somdev Devvarman        2
2           Tobias Kamke        2
3       Julien Benneteau        3
4            Lukas Lacko        1
..                   ...      ...
122          Yen-Hsun Lu        1
123      Grigor Dimitrov        3
124          Guido Pella        2
125         David Goffin        1
126     Janko Tipsarevic        2

[127 rows x 2 columns]

10. Utiliser les deux question précédentes et la méthode `apply` pour compter le nombre de matchs que chaque participant a disputé et ordonner le résultat par ordre décroissant.

In [55]:
rg_joueur.sort_values(by = "n_match", ascending=False)

                     Joueur  n_match
47             Rafael Nadal        7
80             David Ferrer        7
62           Novak Djokovic        6
15       Jo-Wilfried Tsonga        6
54               Tommy Haas        5
..                      ...      ...
114           Daniel Brands        1
122             Yen-Hsun Lu        1
120         Guillaume Rufin        1
119  Guillermo Garcia-Lopez        1
125            David Goffin        1

[127 rows x 2 columns]

11. Charger maintenant le jeu de données relatif au tournoi de Wimbledon dans un dataframe `wb` à partir du fichier `wimbledon2013.csv`.

In [56]:
wb = pd.read_csv("../data/wimbledon2013.csv")

12. Ajouter une colonne `Tournoi` dans les dataframes `rg` et `wb` contenant respectivement les chaînes de caractères `"RG"` et `"WB"`.

In [82]:
rg = tennis

wb["Tournoi"] = "WB"
rg["Tournoi"] = "RG"
rg

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,ACE_tot,Tournoi
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,14,18,88,6,6,6.0,NaN,NaN,11,RG
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,22,25,106,3,3,5.0,NaN,NaN,7,RG
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,19,27,139,3,3,6.0,6.0,3.0,10,RG
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,33,43,149,6,3,7.0,6.0,NaN,27,RG
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,12,13,93,6,6,6.0,NaN,NaN,14,RG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Rafael Nadal,Stanislas Wawrinka,5,1,3,0,75,40,25,11,...,16,30,64,2,3,1.0,NaN,NaN,8,RG
121,Novak Djokovic,Tommy Haas,5,1,3,0,64,41,36,22,...,2,17,84,3,6,5.0,NaN,NaN,15,RG
122,David Ferrer,Jo-Wilfried Tsonga,6,1,3,0,60,35,40,23,...,7,16,84,1,6,2.0,NaN,NaN,9,RG
123,Novak Djokovic,Rafael Nadal,6,0,2,3,67,76,33,30,...,15,26,177,6,3,6.0,6.0,9.0,11,RG
124,Rafael Nadal,David Ferrer,7,1,3,0,70,43,30,11,...,10,14,72,3,2,3.0,NaN,NaN,6,RG

13. Concaténer les deux dataframes dans un nouveau dataframe `tennis`.

In [83]:
tennis = pd.concat([rg, wb], join="inner", ignore_index=True)
tennis

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Tournoi
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,7,14,18,88.0,6,6,6.0,NaN,NaN,RG
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,16,22,25,106.0,3,3,5.0,NaN,NaN,RG
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,18,19,27,139.0,3,3,6.0,6.0,3.0,RG
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,13,33,43,149.0,6,3,7.0,6.0,NaN,RG
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,7,12,13,93.0,6,6,6.0,NaN,NaN,RG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,3,21,17,NaN,6,6,7.0,NaN,NaN,WB
235,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,2,31,21,NaN,6,4,3.0,NaN,NaN,WB
236,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,5,36,22,NaN,6,6,6.0,6.0,NaN,WB
237,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,2,37,25,NaN,5,6,6.0,7.0,3.0,WB
238,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,7,37,26,NaN,6,7,6.0,NaN,NaN,WB

14. Utiliser le dataframe `tennis` pour comparer le nombre moyen d'aces par match à chaque niveau du tournoi à Roland Garros et à Wimbledon. Afficher le résultat en format large.

In [96]:
format_long = (
    tennis
    .assign(ACE_tot=tennis["ACE.1"] + tennis["ACE.2"])
    .groupby(["Tournoi", "Round"])
    ["ACE_tot"].mean()
    .reset_index()
)
format_long

   Tournoi  Round    ACE_tot
0       RG      1  13.476190
1       RG      2  13.193548
2       RG      3  12.562500
3       RG      4   9.125000
4       RG      5   7.000000
5       RG      6  10.000000
6       RG      7   6.000000
7       WB      1  21.125000
8       WB      2  23.869565
9       WB      3  24.000000
10      WB      4  24.375000
11      WB      5  26.500000
12      WB      6  27.500000
13      WB      7  13.000000

15. Quelle différence y a-t-il dans le format des noms des joueurs entre les dataframes `rg` et `wb` ?

In [99]:
format_large =(
    format_long
    .pivot(
        index="Tournoi",
        columns="Round",
        values="ACE_tot"
    )
)

format_large

Round           1          2        3       4     5     6     7
Tournoi
RG       13.47619  13.193548  12.5625   9.125   7.0  10.0   6.0
WB       21.12500  23.869565  24.0000  24.375  26.5  27.5  13.0

16. Construire un dataframe `rg_victoires` avec les trois colonnes suivantes pour le tournoi de Roland Garros :
- `joueur` : nom du joueur tel qu'il est donné dans `rg`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

In [ ]:
# étape 1 : fair eavec 1 seul joueur
joueur = "Roger Federer"
n_victoire1 = len(rg[(rg["Player1"] == joueur) & (rg["Result"] == 1)]) 
n_victoire2 = len(rg[(rg["Player2"] == joueur) & (rg["Result"] == 0)])
n_victoire = n_victoire1 + n_victoire2
n_victoire

4

In [111]:
# étape 2 : généraliser dans une fonction
def n_victoires(df, joueur):
    n_victoire1 = len(df[(df["Player1"] == joueur) & (df["Result"] == 1)]) 
    n_victoire2 = len(df[(df["Player2"] == joueur) & (df["Result"] == 0)])
    n_victoire = n_victoire1 + n_victoire2
    return n_victoire

In [ ]:
# étape 3 : appliquer fonction
n_victoires(rg, "Roger Federer")

4

In [123]:
# étape 4 : intégration dans une variable
rg_victoires = (
    pd.concat([rg["Player1"], rg["Player2"]])
    .drop_duplicates()   # récupérer les valeurs uniques
    .to_frame(name="joueur")  # convertit série en dataframe
    .reset_index(drop=True)  # reset index vec drop = false : ramène la colonne en index en colonne, # reset index avec drop = true : supprime lancienne colonne d'index
    )

rg_victoires["nom_joueur"] = (
    rg_victoires["joueur"]
    .str.split(" ")
    .apply(lambda v: v[-1])
    )

rg_victoires["n_victoire"] = (
    rg_victoires["joueur"]
    .apply(lambda joueur: n_victoires(rg, joueur))
    )

17. Construire un dataframe `wb_victoires` avec les trois colonnes suivantes pour le tournoi de Wimbledon :
- `joueur` : nom du joueur tel qu'il est donné dans `wb`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

In [125]:
wb_victoires = (
    pd.concat([wb["Player1"], wb["Player2"]])
    .drop_duplicates()   # récupérer les valeurs uniques
    .to_frame(name="joueur")  # convertit série en dataframe
    .reset_index(drop=True)  # reset index vec drop = false : ramène la colonne en index en colonne, # reset index avec drop = true : supprime lancienne colonne d'index
)

wb_victoires["nom_joueur"] = (
    wb_victoires["joueur"]
    .str.split(".") # différence de'écriture de nom dans wb
    .apply(lambda v: v[-1])
    )

wb_victoires["n_victoire"] = (
    wb_victoires["joueur"]
    .apply(lambda joueur: n_victoires(wb, joueur))
)

18. Faire une jointure entre `rg_victoires` et `wb_victoires` sur la colonne `nom_joueur` pour comparer le nombre de victoires par tournoi pour chaque joueur. Expliquer la différence de résultat selon que la jointure est à gauche, à droite, intérieure ou extérieure.

In [133]:
pd.merge(rg_victoires, wb_victoires,  on = "nom_joueur", how = "outer", suffixes=("_rg", "_wb"))

,joueur_rg,nom_joueur,n_victoire_rg,joueur_wb,n_victoire_wb
0,NaN,,NaN,A.Bogomolov Jr.,0.0
1,Roberto Bautista Agut,Agut,1.0,NaN,NaN
2,Nicolas Almagro,Almagro,3.0,N.Almagro,2.0
3,Martin Alund,Alund,0.0,M.Alund,0.0
4,Kevin Anderson,Anderson,3.0,K.Anderson,2.0
...,...,...,...,...,...
148,Rhyne Williams,Williams,0.0,NaN,NaN
149,Mikhail Youzhny,Youzhny,3.0,M.Youzhny,2.0
150,Horacio Zeballos,Zeballos,1.0,H.Zeballos,0.0
151,Grega Zemlja,Zemlja,1.0,G.Zemlja,2.0
152,Jurgen Zopp,Zopp,0.0,J.Zopp,0.0

In [ ]:
#autre manière d'écrire - uniquement noms en commun = inner
rg_victoires.merge(
    wb_victoires, 
    on = "nom_joueur", 
    how = "inner", 
    suffixes=("_rg", "_wb")
).drop(columns=["joueur_rg", "joueur_wb"])

     nom_joueur  n_victoire_rg  n_victoire_wb
0         Kamke              1              0
1     Benneteau              2              1
2         Lacko              0              0
3         Hajek              1              0
4     Mannarino              0              2
..          ...            ...            ...
101          Lu              1              1
102    Dimitrov              2              1
103       Pella              1              0
104      Goffin              0              0
105  Tipsarevic              1              0

[106 rows x 3 columns]

In [136]:
#autre manière d'écrire - tous les noms  noms en commun = outer
rg_victoires.merge(
    wb_victoires, 
    on = "nom_joueur", 
    how = "outer", 
    suffixes=("_rg", "_wb")
).drop(columns=["joueur_rg", "joueur_wb"])

    nom_joueur  n_victoire_rg  n_victoire_wb
0                         NaN            0.0
1         Agut            1.0            NaN
2      Almagro            3.0            2.0
3        Alund            0.0            0.0
4     Anderson            3.0            2.0
..         ...            ...            ...
148   Williams            0.0            NaN
149    Youzhny            3.0            2.0
150   Zeballos            1.0            0.0
151     Zemlja            1.0            2.0
152       Zopp            0.0            0.0

[153 rows x 3 columns]