# Notebook 4 : JSON et API

In [3]:
import json
import random

from io import StringIO # Pour éviter les avertissements de read_json

import pandas as pd
import requests

## Format JSON

Nous considérons deux jeux de données artificiels pour illustrer des limites du format JSON à garder à l'esprit en pratique.

In [ ]:
nombres = pd.DataFrame({"Nombre": [random.random() for _ in range(5)]})
nananinf = pd.DataFrame({"Valeur": [3.14, pd.NA, float("nan"), float("inf")]})

1. Convertir `nombres` au format JSON avec la méthode `to_json` et stocker le résultat dans une variable `nombres_json`.

2. Importer `nombres_json` avec la fonction `read_json` de Pandas dans un dataframe `nombres_bis`. Comparer les objets `nombres` et `nombres_bis`.

In [ ]:
# attention, il y a perte d'information en passant par un format texte type JSON, CSV etc
# préférer formats BSON par exemple

3. Lire la documentation de `to_json` pour connaître l'option permettant de gérer (mais pas de résoudre) le problème précédent.

4. Convertir `nananinf` au format JSON avec la méthode `to_json` et stocker le résultat dans une variable `nananinf_json`. Que sont devenus `NA`, `NaN` et `inf` ?

5. Importer `nananinf_json` avec la fonction `read_json` de Pandas dans un dataframe `nananinf_bis`. Comparer les objets `nananinf` et `nananinf_bis`.

6. Reprendre les questions 4 et 5 sur l'objet `[float("nan"), float("inf")]` avec les fonctions `dumps` et `loads`. Quelle est la différence ? Lire la documentation de `dumps` pour comprendre l'option `allow_nan`.

## Iris

Nous reprenons ici le jeu de données des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher) pour étudier les différentes façons d'exporter un dataframe au format JSON.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv`.

In [4]:
iris = pd.read_csv("../data/iris.csv")
iris

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

2. Comparer les résultats obtenus en exportant `iris` au format JSON avec `to_json` et :
- `orient="columns"`,
- `orient="index"`,
- `orient="records"`.

In [6]:
iris.to_json(orient="columns")

'{"SepalLength":{"0":5.1,"1":4.9,"2":4.7,"3":4.6,"4":5.0,"5":5.4,"6":4.6,"7":5.0,"8":4.4,"9":4.9,"10":5.4,"11":4.8,"12":4.8,"13":4.3,"14":5.8,"15":5.7,"16":5.4,"17":5.1,"18":5.7,"19":5.1,"20":5.4,"21":5.1,"22":4.6,"23":5.1,"24":4.8,"25":5.0,"26":5.0,"27":5.2,"28":5.2,"29":4.7,"30":4.8,"31":5.4,"32":5.2,"33":5.5,"34":4.9,"35":5.0,"36":5.5,"37":4.9,"38":4.4,"39":5.1,"40":5.0,"41":4.5,"42":4.4,"43":5.0,"44":5.1,"45":4.8,"46":5.1,"47":4.6,"48":5.3,"49":5.0,"50":7.0,"51":6.4,"52":6.9,"53":5.5,"54":6.5,"55":5.7,"56":6.3,"57":4.9,"58":6.6,"59":5.2,"60":5.0,"61":5.9,"62":6.0,"63":6.1,"64":5.6,"65":6.7,"66":5.6,"67":5.8,"68":6.2,"69":5.6,"70":5.9,"71":6.1,"72":6.3,"73":6.1,"74":6.4,"75":6.6,"76":6.8,"77":6.7,"78":6.0,"79":5.7,"80":5.5,"81":5.5,"82":5.8,"83":6.0,"84":5.4,"85":6.0,"86":6.7,"87":6.3,"88":5.6,"89":5.5,"90":5.5,"91":6.1,"92":5.8,"93":5.0,"94":5.6,"95":5.7,"96":5.7,"97":6.2,"98":5.1,"99":5.7,"100":6.3,"101":5.8,"102":7.1,"103":6.3,"104":6.5,"105":7.6,"106":4.9,"107":7.3,"108":6.7,"109":7.2,"110":6.5,"111":6.4,"112":6.8,"113":5.7,"114":5.8,"115":6.4,"116":6.5,"117":7.7,"118":7.7,"119":6.0,"120":6.9,"121":5.6,"122":7.7,"123":6.3,"124":6.7,"125":7.2,"126":6.2,"127":6.1,"128":6.4,"129":7.2,"130":7.4,"131":7.9,"132":6.4,"133":6.3,"134":6.1,"135":7.7,"136":6.3,"137":6.4,"138":6.0,"139":6.9,"140":6.7,"141":6.9,"142":5.8,"143":6.8,"144":6.7,"145":6.7,"146":6.3,"147":6.5,"148":6.2,"149":5.9},"SepalWidth":{"0":3.5,"1":3.0,"2":3.2,"3":3.1,"4":3.6,"5":3.9,"6":3.4,"7":3.4,"8":2.9,"9":3.1,"10":3.7,"11":3.4,"12":3.0,"13":3.0,"14":4.0,"15":4.4,"16":3.9,"17":3.5,"18":3.8,"19":3.8,"20":3.4,"21":3.7,"22":3.6,"23":3.3,"24":3.4,"25":3.0,"26":3.4,"27":3.5,"28":3.4,"29":3.2,"30":3.1,"31":3.4,"32":4.1,"33":4.2,"34":3.1,"35":3.2,"36":3.5,"37":3.6,"38":3.0,"39":3.4,"40":3.5,"41":2.3,"42":3.2,"43":3.5,"44":3.8,"45":3.0,"46":3.8,"47":3.2,"48":3.7,"49":3.3,"50":3.2,"51":3.2,"52":3.1,"53":2.3,"54":2.8,"55":2.8,"56":3.3,"57":2.4,"58":2.9,"59":2.7,"60":2.0,"61":3.0,"62":2.2,"63":2.9,"64":2.9,"65":3.1,"66":3.0,"67":2.7,"68":2.2,"69":2.5,"70":3.2,"71":2.8,"72":2.5,"73":2.8,"74":2.9,"75":3.0,"76":2.8,"77":3.0,"78":2.9,"79":2.6,"80":2.4,"81":2.4,"82":2.7,"83":2.7,"84":3.0,"85":3.4,"86":3.1,"87":2.3,"88":3.0,"89":2.5,"90":2.6,"91":3.0,"92":2.6,"93":2.3,"94":2.7,"95":3.0,"96":2.9,"97":2.9,"98":2.5,"99":2.8,"100":3.3,"101":2.7,"102":3.0,"103":2.9,"104":3.0,"105":3.0,"106":2.5,"107":2.9,"108":2.5,"109":3.6,"110":3.2,"111":2.7,"112":3.0,"113":2.5,"114":2.8,"115":3.2,"116":3.0,"117":3.8,"118":2.6,"119":2.2,"120":3.2,"121":2.8,"122":2.8,"123":2.7,"124":3.3,"125":3.2,"126":2.8,"127":3.0,"128":2.8,"129":3.0,"130":2.8,"131":3.8,"132":2.8,"133":2.8,"134":2.6,"135":3.0,"136":3.4,"137":3.1,"138":3.0,"139":3.1,"140":3.1,"141":3.1,"142":2.7,"143":3.2,"144":3.3,"145":3.0,"146":2.5,"147":3.0,"148":3.4,"149":3.0},"PetalLength":{"0":1.4,"1":1.4,"2":1.3,"3":1.5,"4":1.4,"5":1.7,"6":1.4,"7":1.5,"8":1.4,"9":1.5,"10":1.5,"11":1.6,"12":1.4,"13":1.1,"14":1.2,"15":1.5,"16":1.3,"17":1.4,"18":1.7,"19":1.5,"20":1.7,"21":1.5,"22":1.0,"23":1.7,"24":1.9,"25":1.6,"26":1.6,"27":1.5,"28":1.4,"29":1.6,"30":1.6,"31":1.5,"32":1.5,"33":1.4,"34":1.5,"35":1.2,"36":1.3,"37":1.4,"38":1.3,"39":1.5,"40":1.3,"41":1.3,"42":1.3,"43":1.6,"44":1.9,"45":1.4,"46":1.6,"47":1.4,"48":1.5,"49":1.4,"50":4.7,"51":4.5,"52":4.9,"53":4.0,"54":4.6,"55":4.5,"56":4.7,"57":3.3,"58":4.6,"59":3.9,"60":3.5,"61":4.2,"62":4.0,"63":4.7,"64":3.6,"65":4.4,"66":4.5,"67":4.1,"68":4.5,"69":3.9,"70":4.8,"71":4.0,"72":4.9,"73":4.7,"74":4.3,"75":4.4,"76":4.8,"77":5.0,"78":4.5,"79":3.5,"80":3.8,"81":3.7,"82":3.9,"83":5.1,"84":4.5,"85":4.5,"86":4.7,"87":4.4,"88":4.1,"89":4.0,"90":4.4,"91":4.6,"92":4.0,"93":3.3,"94":4.2,"95":4.2,"96":4.2,"97":4.3,"98":3.0,"99":4.1,"100":6.0,"101":5.1,"102":5.9,"103":5.6,"104":5.8,"105":6.6,"106":4.5,"107":6.3,"108":5.8,"109":6.1,"110":5.1,"111":5.3,"112":5.5,"113":5.0,"114":5.1,"115":5.3,"116":5.5,"117":6.7,"118":6.9,"119":5.0,"120":5.7,"121":4.9,"122":6.7,"123":4.9,"124":5.7,"125":6.0,"126":4.8,"127":4.9,"128":5.6,"129":5.8,"130":6.1,"131":6.4,"132":5.6,"133":5.1,"134":5.6,"135":6.1,"136":5.6,"137":5.5,"138":4.8,"139":5.4,"140":5.6,"141":5.1,"142":5.1,"143":5.9,"144":5.7,"145":5.2,"146":5.0,"147":5.2,"148":5.4,"149":5.1},"PetalWidth":{"0":0.2,"1":0.2,"2":0.2,"3":0.2,"4":0.2,"5":0.4,"6":0.3,"7":0.2,"8":0.2,"9":0.1,"10":0.2,"11":0.2,"12":0.1,"13":0.1,"14":0.2,"15":0.4,"16":0.4,"17":0.3,"18":0.3,"19":0.3,"20":0.2,"21":0.4,"22":0.2,"23":0.5,"24":0.2,"25":0.2,"26":0.4,"27":0.2,"28":0.2,"29":0.2,"30":0.2,"31":0.4,"32":0.1,"33":0.2,"34":0.2,"35":0.2,"36":0.2,"37":0.1,"38":0.2,"39":0.2,"40":0.3,"41":0.3,"42":0.2,"43":0.6,"44":0.4,"45":0.3,"46":0.2,"47":0.2,"48":0.2,"49":0.2,"50":1.4,"51":1.5,"52":1.5,"53":1.3,"54":1.5,"55":1.3,"56":1.6,"57":1.0,"58":1.3,"59":1.4,"60":1.0,"61":1.5,"62":1.0,"63":1.4,"64":1.3,"65":1.4,"66":1.5,"67":1.0,"68":1.5,"69":1.1,"70":1.8,"71":1.3,"72":1.5,"73":1.2,"74":1.3,"75":1.4,"76":1.4,"77":1.7,"78":1.5,"79":1.0,"80":1.1,"81":1.0,"82":1.2,"83":1.6,"84":1.5,"85":1.6,"86":1.5,"87":1.3,"88":1.3,"89":1.3,"90":1.2,"91":1.4,"92":1.2,"93":1.0,"94":1.3,"95":1.2,"96":1.3,"97":1.3,"98":1.1,"99":1.3,"100":2.5,"101":1.9,"102":2.1,"103":1.8,"104":2.2,"105":2.1,"106":1.7,"107":1.8,"108":1.8,"109":2.5,"110":2.0,"111":1.9,"112":2.1,"113":2.0,"114":2.4,"115":2.3,"116":1.8,"117":2.2,"118":2.3,"119":1.5,"120":2.3,"121":2.0,"122":2.0,"123":1.8,"124":2.1,"125":1.8,"126":1.8,"127":1.8,"128":2.1,"129":1.6,"130":1.9,"131":2.0,"132":2.2,"133":1.5,"134":1.4,"135":2.3,"136":2.4,"137":1.8,"138":1.8,"139":2.1,"140":2.4,"141":2.3,"142":1.9,"143":2.3,"144":2.5,"145":2.3,"146":1.9,"147":2.0,"148":2.3,"149":1.8},"Species":{"0":"setosa","1":"setosa","2":"setosa","3":"setosa","4":"setosa","5":"setosa","6":"setosa","7":"setosa","8":"setosa","9":"setosa","10":"setosa","11":"setosa","12":"setosa","13":"setosa","14":"setosa","15":"setosa","16":"setosa","17":"setosa","18":"setosa","19":"setosa","20":"setosa","21":"setosa","22":"setosa","23":"setosa","24":"setosa","25":"setosa","26":"setosa","27":"setosa","28":"setosa","29":"setosa","30":"setosa","31":"setosa","32":"setosa","33":"setosa","34":"setosa","35":"setosa","36":"setosa","37":"setosa","38":"setosa","39":"setosa","40":"setosa","41":"setosa","42":"setosa","43":"setosa","44":"setosa","45":"setosa","46":"setosa","47":"setosa","48":"setosa","49":"setosa","50":"versicolor","51":"versicolor","52":"versicolor","53":"versicolor","54":"versicolor","55":"versicolor","56":"versicolor","57":"versicolor","58":"versicolor","59":"versicolor","60":"versicolor","61":"versicolor","62":"versicolor","63":"versicolor","64":"versicolor","65":"versicolor","66":"versicolor","67":"versicolor","68":"versicolor","69":"versicolor","70":"versicolor","71":"versicolor","72":"versicolor","73":"versicolor","74":"versicolor","75":"versicolor","76":"versicolor","77":"versicolor","78":"versicolor","79":"versicolor","80":"versicolor","81":"versicolor","82":"versicolor","83":"versicolor","84":"versicolor","85":"versicolor","86":"versicolor","87":"versicolor","88":"versicolor","89":"versicolor","90":"versicolor","91":"versicolor","92":"versicolor","93":"versicolor","94":"versicolor","95":"versicolor","96":"versicolor","97":"versicolor","98":"versicolor","99":"versicolor","100":"virginica","101":"virginica","102":"virginica","103":"virginica","104":"virginica","105":"virginica","106":"virginica","107":"virginica","108":"virginica","109":"virginica","110":"virginica","111":"virginica","112":"virginica","113":"virginica","114":"virginica","115":"virginica","116":"virginica","117":"virginica","118":"virginica","119":"virginica","120":"virginica","121":"virginica","122":"virginica","123":"virginica","124":"virginica","125":"virginica","126":"virginica","127":"virginica","128":"virginica","129":"virginica","130":"virginica","131":"virginica","132":"virginica","133":"virginica","134":"virginica","135":"virginica","136":"virginica","137":"virginica","138":"virginica","139":"virginica","140":"virginica","141":"virginica","142":"virginica","143":"virginica","144":"virginica","145":"virginica","146":"virginica","147":"virginica","148":"virginica","149":"virginica"}}'

In [7]:
iris.to_json(orient="index")

'{"0":{"SepalLength":5.1,"SepalWidth":3.5,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"1":{"SepalLength":4.9,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"2":{"SepalLength":4.7,"SepalWidth":3.2,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},"3":{"SepalLength":4.6,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"4":{"SepalLength":5.0,"SepalWidth":3.6,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"5":{"SepalLength":5.4,"SepalWidth":3.9,"PetalLength":1.7,"PetalWidth":0.4,"Species":"setosa"},"6":{"SepalLength":4.6,"SepalWidth":3.4,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},"7":{"SepalLength":5.0,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"8":{"SepalLength":4.4,"SepalWidth":2.9,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"9":{"SepalLength":4.9,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.1,"Species":"setosa"},"10":{"SepalLength":5.4,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"11":{"SepalLength":4.8,"SepalWidth":3.4,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},"12":{"SepalLength":4.8,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.1,"Species":"setosa"},"13":{"SepalLength":4.3,"SepalWidth":3.0,"PetalLength":1.1,"PetalWidth":0.1,"Species":"setosa"},"14":{"SepalLength":5.8,"SepalWidth":4.0,"PetalLength":1.2,"PetalWidth":0.2,"Species":"setosa"},"15":{"SepalLength":5.7,"SepalWidth":4.4,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},"16":{"SepalLength":5.4,"SepalWidth":3.9,"PetalLength":1.3,"PetalWidth":0.4,"Species":"setosa"},"17":{"SepalLength":5.1,"SepalWidth":3.5,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},"18":{"SepalLength":5.7,"SepalWidth":3.8,"PetalLength":1.7,"PetalWidth":0.3,"Species":"setosa"},"19":{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.5,"PetalWidth":0.3,"Species":"setosa"},"20":{"SepalLength":5.4,"SepalWidth":3.4,"PetalLength":1.7,"PetalWidth":0.2,"Species":"setosa"},"21":{"SepalLength":5.1,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},"22":{"SepalLength":4.6,"SepalWidth":3.6,"PetalLength":1.0,"PetalWidth":0.2,"Species":"setosa"},"23":{"SepalLength":5.1,"SepalWidth":3.3,"PetalLength":1.7,"PetalWidth":0.5,"Species":"setosa"},"24":{"SepalLength":4.8,"SepalWidth":3.4,"PetalLength":1.9,"PetalWidth":0.2,"Species":"setosa"},"25":{"SepalLength":5.0,"SepalWidth":3.0,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},"26":{"SepalLength":5.0,"SepalWidth":3.4,"PetalLength":1.6,"PetalWidth":0.4,"Species":"setosa"},"27":{"SepalLength":5.2,"SepalWidth":3.5,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"28":{"SepalLength":5.2,"SepalWidth":3.4,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"29":{"SepalLength":4.7,"SepalWidth":3.2,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},"30":{"SepalLength":4.8,"SepalWidth":3.1,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},"31":{"SepalLength":5.4,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},"32":{"SepalLength":5.2,"SepalWidth":4.1,"PetalLength":1.5,"PetalWidth":0.1,"Species":"setosa"},"33":{"SepalLength":5.5,"SepalWidth":4.2,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"34":{"SepalLength":4.9,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"35":{"SepalLength":5.0,"SepalWidth":3.2,"PetalLength":1.2,"PetalWidth":0.2,"Species":"setosa"},"36":{"SepalLength":5.5,"SepalWidth":3.5,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},"37":{"SepalLength":4.9,"SepalWidth":3.6,"PetalLength":1.4,"PetalWidth":0.1,"Species":"setosa"},"38":{"SepalLength":4.4,"SepalWidth":3.0,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},"39":{"SepalLength":5.1,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"40":{"SepalLength":5.0,"SepalWidth":3.5,"PetalLength":1.3,"PetalWidth":0.3,"Species":"setosa"},"41":{"SepalLength":4.5,"SepalWidth":2.3,"PetalLength":1.3,"PetalWidth":0.3,"Species":"setosa"},"42":{"SepalLength":4.4,"SepalWidth":3.2,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},"43":{"SepalLength":5.0,"SepalWidth":3.5,"PetalLength":1.6,"PetalWidth":0.6,"Species":"setosa"},"44":{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.9,"PetalWidth":0.4,"Species":"setosa"},"45":{"SepalLength":4.8,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},"46":{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},"47":{"SepalLength":4.6,"SepalWidth":3.2,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"48":{"SepalLength":5.3,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},"49":{"SepalLength":5.0,"SepalWidth":3.3,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},"50":{"SepalLength":7.0,"SepalWidth":3.2,"PetalLength":4.7,"PetalWidth":1.4,"Species":"versicolor"},"51":{"SepalLength":6.4,"SepalWidth":3.2,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},"52":{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":4.9,"PetalWidth":1.5,"Species":"versicolor"},"53":{"SepalLength":5.5,"SepalWidth":2.3,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},"54":{"SepalLength":6.5,"SepalWidth":2.8,"PetalLength":4.6,"PetalWidth":1.5,"Species":"versicolor"},"55":{"SepalLength":5.7,"SepalWidth":2.8,"PetalLength":4.5,"PetalWidth":1.3,"Species":"versicolor"},"56":{"SepalLength":6.3,"SepalWidth":3.3,"PetalLength":4.7,"PetalWidth":1.6,"Species":"versicolor"},"57":{"SepalLength":4.9,"SepalWidth":2.4,"PetalLength":3.3,"PetalWidth":1.0,"Species":"versicolor"},"58":{"SepalLength":6.6,"SepalWidth":2.9,"PetalLength":4.6,"PetalWidth":1.3,"Species":"versicolor"},"59":{"SepalLength":5.2,"SepalWidth":2.7,"PetalLength":3.9,"PetalWidth":1.4,"Species":"versicolor"},"60":{"SepalLength":5.0,"SepalWidth":2.0,"PetalLength":3.5,"PetalWidth":1.0,"Species":"versicolor"},"61":{"SepalLength":5.9,"SepalWidth":3.0,"PetalLength":4.2,"PetalWidth":1.5,"Species":"versicolor"},"62":{"SepalLength":6.0,"SepalWidth":2.2,"PetalLength":4.0,"PetalWidth":1.0,"Species":"versicolor"},"63":{"SepalLength":6.1,"SepalWidth":2.9,"PetalLength":4.7,"PetalWidth":1.4,"Species":"versicolor"},"64":{"SepalLength":5.6,"SepalWidth":2.9,"PetalLength":3.6,"PetalWidth":1.3,"Species":"versicolor"},"65":{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":4.4,"PetalWidth":1.4,"Species":"versicolor"},"66":{"SepalLength":5.6,"SepalWidth":3.0,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},"67":{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":4.1,"PetalWidth":1.0,"Species":"versicolor"},"68":{"SepalLength":6.2,"SepalWidth":2.2,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},"69":{"SepalLength":5.6,"SepalWidth":2.5,"PetalLength":3.9,"PetalWidth":1.1,"Species":"versicolor"},"70":{"SepalLength":5.9,"SepalWidth":3.2,"PetalLength":4.8,"PetalWidth":1.8,"Species":"versicolor"},"71":{"SepalLength":6.1,"SepalWidth":2.8,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},"72":{"SepalLength":6.3,"SepalWidth":2.5,"PetalLength":4.9,"PetalWidth":1.5,"Species":"versicolor"},"73":{"SepalLength":6.1,"SepalWidth":2.8,"PetalLength":4.7,"PetalWidth":1.2,"Species":"versicolor"},"74":{"SepalLength":6.4,"SepalWidth":2.9,"PetalLength":4.3,"PetalWidth":1.3,"Species":"versicolor"},"75":{"SepalLength":6.6,"SepalWidth":3.0,"PetalLength":4.4,"PetalWidth":1.4,"Species":"versicolor"},"76":{"SepalLength":6.8,"SepalWidth":2.8,"PetalLength":4.8,"PetalWidth":1.4,"Species":"versicolor"},"77":{"SepalLength":6.7,"SepalWidth":3.0,"PetalLength":5.0,"PetalWidth":1.7,"Species":"versicolor"},"78":{"SepalLength":6.0,"SepalWidth":2.9,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},"79":{"SepalLength":5.7,"SepalWidth":2.6,"PetalLength":3.5,"PetalWidth":1.0,"Species":"versicolor"},"80":{"SepalLength":5.5,"SepalWidth":2.4,"PetalLength":3.8,"PetalWidth":1.1,"Species":"versicolor"},"81":{"SepalLength":5.5,"SepalWidth":2.4,"PetalLength":3.7,"PetalWidth":1.0,"Species":"versicolor"},"82":{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":3.9,"PetalWidth":1.2,"Species":"versicolor"},"83":{"SepalLength":6.0,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.6,"Species":"versicolor"},"84":{"SepalLength":5.4,"SepalWidth":3.0,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},"85":{"SepalLength":6.0,"SepalWidth":3.4,"PetalLength":4.5,"PetalWidth":1.6,"Species":"versicolor"},"86":{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":4.7,"PetalWidth":1.5,"Species":"versicolor"},"87":{"SepalLength":6.3,"SepalWidth":2.3,"PetalLength":4.4,"PetalWidth":1.3,"Species":"versicolor"},"88":{"SepalLength":5.6,"SepalWidth":3.0,"PetalLength":4.1,"PetalWidth":1.3,"Species":"versicolor"},"89":{"SepalLength":5.5,"SepalWidth":2.5,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},"90":{"SepalLength":5.5,"SepalWidth":2.6,"PetalLength":4.4,"PetalWidth":1.2,"Species":"versicolor"},"91":{"SepalLength":6.1,"SepalWidth":3.0,"PetalLength":4.6,"PetalWidth":1.4,"Species":"versicolor"},"92":{"SepalLength":5.8,"SepalWidth":2.6,"PetalLength":4.0,"PetalWidth":1.2,"Species":"versicolor"},"93":{"SepalLength":5.0,"SepalWidth":2.3,"PetalLength":3.3,"PetalWidth":1.0,"Species":"versicolor"},"94":{"SepalLength":5.6,"SepalWidth":2.7,"PetalLength":4.2,"PetalWidth":1.3,"Species":"versicolor"},"95":{"SepalLength":5.7,"SepalWidth":3.0,"PetalLength":4.2,"PetalWidth":1.2,"Species":"versicolor"},"96":{"SepalLength":5.7,"SepalWidth":2.9,"PetalLength":4.2,"PetalWidth":1.3,"Species":"versicolor"},"97":{"SepalLength":6.2,"SepalWidth":2.9,"PetalLength":4.3,"PetalWidth":1.3,"Species":"versicolor"},"98":{"SepalLength":5.1,"SepalWidth":2.5,"PetalLength":3.0,"PetalWidth":1.1,"Species":"versicolor"},"99":{"SepalLength":5.7,"SepalWidth":2.8,"PetalLength":4.1,"PetalWidth":1.3,"Species":"versicolor"},"100":{"SepalLength":6.3,"SepalWidth":3.3,"PetalLength":6.0,"PetalWidth":2.5,"Species":"virginica"},"101":{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.9,"Species":"virginica"},"102":{"SepalLength":7.1,"SepalWidth":3.0,"PetalLength":5.9,"PetalWidth":2.1,"Species":"virginica"},"103":{"SepalLength":6.3,"SepalWidth":2.9,"PetalLength":5.6,"PetalWidth":1.8,"Species":"virginica"},"104":{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.8,"PetalWidth":2.2,"Species":"virginica"},"105":{"SepalLength":7.6,"SepalWidth":3.0,"PetalLength":6.6,"PetalWidth":2.1,"Species":"virginica"},"106":{"SepalLength":4.9,"SepalWidth":2.5,"PetalLength":4.5,"PetalWidth":1.7,"Species":"virginica"},"107":{"SepalLength":7.3,"SepalWidth":2.9,"PetalLength":6.3,"PetalWidth":1.8,"Species":"virginica"},"108":{"SepalLength":6.7,"SepalWidth":2.5,"PetalLength":5.8,"PetalWidth":1.8,"Species":"virginica"},"109":{"SepalLength":7.2,"SepalWidth":3.6,"PetalLength":6.1,"PetalWidth":2.5,"Species":"virginica"},"110":{"SepalLength":6.5,"SepalWidth":3.2,"PetalLength":5.1,"PetalWidth":2.0,"Species":"virginica"},"111":{"SepalLength":6.4,"SepalWidth":2.7,"PetalLength":5.3,"PetalWidth":1.9,"Species":"virginica"},"112":{"SepalLength":6.8,"SepalWidth":3.0,"PetalLength":5.5,"PetalWidth":2.1,"Species":"virginica"},"113":{"SepalLength":5.7,"SepalWidth":2.5,"PetalLength":5.0,"PetalWidth":2.0,"Species":"virginica"},"114":{"SepalLength":5.8,"SepalWidth":2.8,"PetalLength":5.1,"PetalWidth":2.4,"Species":"virginica"},"115":{"SepalLength":6.4,"SepalWidth":3.2,"PetalLength":5.3,"PetalWidth":2.3,"Species":"virginica"},"116":{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.5,"PetalWidth":1.8,"Species":"virginica"},"117":{"SepalLength":7.7,"SepalWidth":3.8,"PetalLength":6.7,"PetalWidth":2.2,"Species":"virginica"},"118":{"SepalLength":7.7,"SepalWidth":2.6,"PetalLength":6.9,"PetalWidth":2.3,"Species":"virginica"},"119":{"SepalLength":6.0,"SepalWidth":2.2,"PetalLength":5.0,"PetalWidth":1.5,"Species":"virginica"},"120":{"SepalLength":6.9,"SepalWidth":3.2,"PetalLength":5.7,"PetalWidth":2.3,"Species":"virginica"},"121":{"SepalLength":5.6,"SepalWidth":2.8,"PetalLength":4.9,"PetalWidth":2.0,"Species":"virginica"},"122":{"SepalLength":7.7,"SepalWidth":2.8,"PetalLength":6.7,"PetalWidth":2.0,"Species":"virginica"},"123":{"SepalLength":6.3,"SepalWidth":2.7,"PetalLength":4.9,"PetalWidth":1.8,"Species":"virginica"},"124":{"SepalLength":6.7,"SepalWidth":3.3,"PetalLength":5.7,"PetalWidth":2.1,"Species":"virginica"},"125":{"SepalLength":7.2,"SepalWidth":3.2,"PetalLength":6.0,"PetalWidth":1.8,"Species":"virginica"},"126":{"SepalLength":6.2,"SepalWidth":2.8,"PetalLength":4.8,"PetalWidth":1.8,"Species":"virginica"},"127":{"SepalLength":6.1,"SepalWidth":3.0,"PetalLength":4.9,"PetalWidth":1.8,"Species":"virginica"},"128":{"SepalLength":6.4,"SepalWidth":2.8,"PetalLength":5.6,"PetalWidth":2.1,"Species":"virginica"},"129":{"SepalLength":7.2,"SepalWidth":3.0,"PetalLength":5.8,"PetalWidth":1.6,"Species":"virginica"},"130":{"SepalLength":7.4,"SepalWidth":2.8,"PetalLength":6.1,"PetalWidth":1.9,"Species":"virginica"},"131":{"SepalLength":7.9,"SepalWidth":3.8,"PetalLength":6.4,"PetalWidth":2.0,"Species":"virginica"},"132":{"SepalLength":6.4,"SepalWidth":2.8,"PetalLength":5.6,"PetalWidth":2.2,"Species":"virginica"},"133":{"SepalLength":6.3,"SepalWidth":2.8,"PetalLength":5.1,"PetalWidth":1.5,"Species":"virginica"},"134":{"SepalLength":6.1,"SepalWidth":2.6,"PetalLength":5.6,"PetalWidth":1.4,"Species":"virginica"},"135":{"SepalLength":7.7,"SepalWidth":3.0,"PetalLength":6.1,"PetalWidth":2.3,"Species":"virginica"},"136":{"SepalLength":6.3,"SepalWidth":3.4,"PetalLength":5.6,"PetalWidth":2.4,"Species":"virginica"},"137":{"SepalLength":6.4,"SepalWidth":3.1,"PetalLength":5.5,"PetalWidth":1.8,"Species":"virginica"},"138":{"SepalLength":6.0,"SepalWidth":3.0,"PetalLength":4.8,"PetalWidth":1.8,"Species":"virginica"},"139":{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":5.4,"PetalWidth":2.1,"Species":"virginica"},"140":{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":5.6,"PetalWidth":2.4,"Species":"virginica"},"141":{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":5.1,"PetalWidth":2.3,"Species":"virginica"},"142":{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.9,"Species":"virginica"},"143":{"SepalLength":6.8,"SepalWidth":3.2,"PetalLength":5.9,"PetalWidth":2.3,"Species":"virginica"},"144":{"SepalLength":6.7,"SepalWidth":3.3,"PetalLength":5.7,"PetalWidth":2.5,"Species":"virginica"},"145":{"SepalLength":6.7,"SepalWidth":3.0,"PetalLength":5.2,"PetalWidth":2.3,"Species":"virginica"},"146":{"SepalLength":6.3,"SepalWidth":2.5,"PetalLength":5.0,"PetalWidth":1.9,"Species":"virginica"},"147":{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.2,"PetalWidth":2.0,"Species":"virginica"},"148":{"SepalLength":6.2,"SepalWidth":3.4,"PetalLength":5.4,"PetalWidth":2.3,"Species":"virginica"},"149":{"SepalLength":5.9,"SepalWidth":3.0,"PetalLength":5.1,"PetalWidth":1.8,"Species":"virginica"}}'

In [8]:
iris.to_json(orient="records")

'[{"SepalLength":5.1,"SepalWidth":3.5,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.9,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.7,"SepalWidth":3.2,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.6,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.6,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.4,"SepalWidth":3.9,"PetalLength":1.7,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":4.6,"SepalWidth":3.4,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.4,"SepalWidth":2.9,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.9,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.1,"Species":"setosa"},{"SepalLength":5.4,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.8,"SepalWidth":3.4,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.8,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.1,"Species":"setosa"},{"SepalLength":4.3,"SepalWidth":3.0,"PetalLength":1.1,"PetalWidth":0.1,"Species":"setosa"},{"SepalLength":5.8,"SepalWidth":4.0,"PetalLength":1.2,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.7,"SepalWidth":4.4,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":5.4,"SepalWidth":3.9,"PetalLength":1.3,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.5,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":5.7,"SepalWidth":3.8,"PetalLength":1.7,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.5,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":5.4,"SepalWidth":3.4,"PetalLength":1.7,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":4.6,"SepalWidth":3.6,"PetalLength":1.0,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.3,"PetalLength":1.7,"PetalWidth":0.5,"Species":"setosa"},{"SepalLength":4.8,"SepalWidth":3.4,"PetalLength":1.9,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.0,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.4,"PetalLength":1.6,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":5.2,"SepalWidth":3.5,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.2,"SepalWidth":3.4,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.7,"SepalWidth":3.2,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.8,"SepalWidth":3.1,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.4,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":5.2,"SepalWidth":4.1,"PetalLength":1.5,"PetalWidth":0.1,"Species":"setosa"},{"SepalLength":5.5,"SepalWidth":4.2,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.9,"SepalWidth":3.1,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.2,"PetalLength":1.2,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.5,"SepalWidth":3.5,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.9,"SepalWidth":3.6,"PetalLength":1.4,"PetalWidth":0.1,"Species":"setosa"},{"SepalLength":4.4,"SepalWidth":3.0,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.4,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.5,"PetalLength":1.3,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":4.5,"SepalWidth":2.3,"PetalLength":1.3,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":4.4,"SepalWidth":3.2,"PetalLength":1.3,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.5,"PetalLength":1.6,"PetalWidth":0.6,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.9,"PetalWidth":0.4,"Species":"setosa"},{"SepalLength":4.8,"SepalWidth":3.0,"PetalLength":1.4,"PetalWidth":0.3,"Species":"setosa"},{"SepalLength":5.1,"SepalWidth":3.8,"PetalLength":1.6,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":4.6,"SepalWidth":3.2,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.3,"SepalWidth":3.7,"PetalLength":1.5,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":5.0,"SepalWidth":3.3,"PetalLength":1.4,"PetalWidth":0.2,"Species":"setosa"},{"SepalLength":7.0,"SepalWidth":3.2,"PetalLength":4.7,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":6.4,"SepalWidth":3.2,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":4.9,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":5.5,"SepalWidth":2.3,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.5,"SepalWidth":2.8,"PetalLength":4.6,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":5.7,"SepalWidth":2.8,"PetalLength":4.5,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.3,"SepalWidth":3.3,"PetalLength":4.7,"PetalWidth":1.6,"Species":"versicolor"},{"SepalLength":4.9,"SepalWidth":2.4,"PetalLength":3.3,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":6.6,"SepalWidth":2.9,"PetalLength":4.6,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.2,"SepalWidth":2.7,"PetalLength":3.9,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":5.0,"SepalWidth":2.0,"PetalLength":3.5,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":5.9,"SepalWidth":3.0,"PetalLength":4.2,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":6.0,"SepalWidth":2.2,"PetalLength":4.0,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":6.1,"SepalWidth":2.9,"PetalLength":4.7,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":5.6,"SepalWidth":2.9,"PetalLength":3.6,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":4.4,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":5.6,"SepalWidth":3.0,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":4.1,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":6.2,"SepalWidth":2.2,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":5.6,"SepalWidth":2.5,"PetalLength":3.9,"PetalWidth":1.1,"Species":"versicolor"},{"SepalLength":5.9,"SepalWidth":3.2,"PetalLength":4.8,"PetalWidth":1.8,"Species":"versicolor"},{"SepalLength":6.1,"SepalWidth":2.8,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.3,"SepalWidth":2.5,"PetalLength":4.9,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":6.1,"SepalWidth":2.8,"PetalLength":4.7,"PetalWidth":1.2,"Species":"versicolor"},{"SepalLength":6.4,"SepalWidth":2.9,"PetalLength":4.3,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.6,"SepalWidth":3.0,"PetalLength":4.4,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":6.8,"SepalWidth":2.8,"PetalLength":4.8,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":6.7,"SepalWidth":3.0,"PetalLength":5.0,"PetalWidth":1.7,"Species":"versicolor"},{"SepalLength":6.0,"SepalWidth":2.9,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":5.7,"SepalWidth":2.6,"PetalLength":3.5,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":5.5,"SepalWidth":2.4,"PetalLength":3.8,"PetalWidth":1.1,"Species":"versicolor"},{"SepalLength":5.5,"SepalWidth":2.4,"PetalLength":3.7,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":3.9,"PetalWidth":1.2,"Species":"versicolor"},{"SepalLength":6.0,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.6,"Species":"versicolor"},{"SepalLength":5.4,"SepalWidth":3.0,"PetalLength":4.5,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":6.0,"SepalWidth":3.4,"PetalLength":4.5,"PetalWidth":1.6,"Species":"versicolor"},{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":4.7,"PetalWidth":1.5,"Species":"versicolor"},{"SepalLength":6.3,"SepalWidth":2.3,"PetalLength":4.4,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.6,"SepalWidth":3.0,"PetalLength":4.1,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.5,"SepalWidth":2.5,"PetalLength":4.0,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.5,"SepalWidth":2.6,"PetalLength":4.4,"PetalWidth":1.2,"Species":"versicolor"},{"SepalLength":6.1,"SepalWidth":3.0,"PetalLength":4.6,"PetalWidth":1.4,"Species":"versicolor"},{"SepalLength":5.8,"SepalWidth":2.6,"PetalLength":4.0,"PetalWidth":1.2,"Species":"versicolor"},{"SepalLength":5.0,"SepalWidth":2.3,"PetalLength":3.3,"PetalWidth":1.0,"Species":"versicolor"},{"SepalLength":5.6,"SepalWidth":2.7,"PetalLength":4.2,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.7,"SepalWidth":3.0,"PetalLength":4.2,"PetalWidth":1.2,"Species":"versicolor"},{"SepalLength":5.7,"SepalWidth":2.9,"PetalLength":4.2,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.2,"SepalWidth":2.9,"PetalLength":4.3,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":5.1,"SepalWidth":2.5,"PetalLength":3.0,"PetalWidth":1.1,"Species":"versicolor"},{"SepalLength":5.7,"SepalWidth":2.8,"PetalLength":4.1,"PetalWidth":1.3,"Species":"versicolor"},{"SepalLength":6.3,"SepalWidth":3.3,"PetalLength":6.0,"PetalWidth":2.5,"Species":"virginica"},{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.9,"Species":"virginica"},{"SepalLength":7.1,"SepalWidth":3.0,"PetalLength":5.9,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":6.3,"SepalWidth":2.9,"PetalLength":5.6,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.8,"PetalWidth":2.2,"Species":"virginica"},{"SepalLength":7.6,"SepalWidth":3.0,"PetalLength":6.6,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":4.9,"SepalWidth":2.5,"PetalLength":4.5,"PetalWidth":1.7,"Species":"virginica"},{"SepalLength":7.3,"SepalWidth":2.9,"PetalLength":6.3,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.7,"SepalWidth":2.5,"PetalLength":5.8,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":7.2,"SepalWidth":3.6,"PetalLength":6.1,"PetalWidth":2.5,"Species":"virginica"},{"SepalLength":6.5,"SepalWidth":3.2,"PetalLength":5.1,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":6.4,"SepalWidth":2.7,"PetalLength":5.3,"PetalWidth":1.9,"Species":"virginica"},{"SepalLength":6.8,"SepalWidth":3.0,"PetalLength":5.5,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":5.7,"SepalWidth":2.5,"PetalLength":5.0,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":5.8,"SepalWidth":2.8,"PetalLength":5.1,"PetalWidth":2.4,"Species":"virginica"},{"SepalLength":6.4,"SepalWidth":3.2,"PetalLength":5.3,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.5,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":7.7,"SepalWidth":3.8,"PetalLength":6.7,"PetalWidth":2.2,"Species":"virginica"},{"SepalLength":7.7,"SepalWidth":2.6,"PetalLength":6.9,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":6.0,"SepalWidth":2.2,"PetalLength":5.0,"PetalWidth":1.5,"Species":"virginica"},{"SepalLength":6.9,"SepalWidth":3.2,"PetalLength":5.7,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":5.6,"SepalWidth":2.8,"PetalLength":4.9,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":7.7,"SepalWidth":2.8,"PetalLength":6.7,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":6.3,"SepalWidth":2.7,"PetalLength":4.9,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.7,"SepalWidth":3.3,"PetalLength":5.7,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":7.2,"SepalWidth":3.2,"PetalLength":6.0,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.2,"SepalWidth":2.8,"PetalLength":4.8,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.1,"SepalWidth":3.0,"PetalLength":4.9,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.4,"SepalWidth":2.8,"PetalLength":5.6,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":7.2,"SepalWidth":3.0,"PetalLength":5.8,"PetalWidth":1.6,"Species":"virginica"},{"SepalLength":7.4,"SepalWidth":2.8,"PetalLength":6.1,"PetalWidth":1.9,"Species":"virginica"},{"SepalLength":7.9,"SepalWidth":3.8,"PetalLength":6.4,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":6.4,"SepalWidth":2.8,"PetalLength":5.6,"PetalWidth":2.2,"Species":"virginica"},{"SepalLength":6.3,"SepalWidth":2.8,"PetalLength":5.1,"PetalWidth":1.5,"Species":"virginica"},{"SepalLength":6.1,"SepalWidth":2.6,"PetalLength":5.6,"PetalWidth":1.4,"Species":"virginica"},{"SepalLength":7.7,"SepalWidth":3.0,"PetalLength":6.1,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":6.3,"SepalWidth":3.4,"PetalLength":5.6,"PetalWidth":2.4,"Species":"virginica"},{"SepalLength":6.4,"SepalWidth":3.1,"PetalLength":5.5,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.0,"SepalWidth":3.0,"PetalLength":4.8,"PetalWidth":1.8,"Species":"virginica"},{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":5.4,"PetalWidth":2.1,"Species":"virginica"},{"SepalLength":6.7,"SepalWidth":3.1,"PetalLength":5.6,"PetalWidth":2.4,"Species":"virginica"},{"SepalLength":6.9,"SepalWidth":3.1,"PetalLength":5.1,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":5.8,"SepalWidth":2.7,"PetalLength":5.1,"PetalWidth":1.9,"Species":"virginica"},{"SepalLength":6.8,"SepalWidth":3.2,"PetalLength":5.9,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":6.7,"SepalWidth":3.3,"PetalLength":5.7,"PetalWidth":2.5,"Species":"virginica"},{"SepalLength":6.7,"SepalWidth":3.0,"PetalLength":5.2,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":6.3,"SepalWidth":2.5,"PetalLength":5.0,"PetalWidth":1.9,"Species":"virginica"},{"SepalLength":6.5,"SepalWidth":3.0,"PetalLength":5.2,"PetalWidth":2.0,"Species":"virginica"},{"SepalLength":6.2,"SepalWidth":3.4,"PetalLength":5.4,"PetalWidth":2.3,"Species":"virginica"},{"SepalLength":5.9,"SepalWidth":3.0,"PetalLength":5.1,"PetalWidth":1.8,"Species":"virginica"}]'

3. Exporter `iris` dans un fichier `iris.json` au format NDJSON. Ouvrir ce fichier dans un éditeur de texte pour vérifier que chaque ligne contient un document.

In [ ]:
# lines = True => format NDJSON avec un objet par ligne
iris_json = iris.to_json("iris.json", orient="records", lines=True)

In [ ]:
# ouvrir lee fichier iris.json

4. Importer le fichier `iris.json` au format NDJSON dans un dataframe `iris2`.

In [18]:
iris2 = pd.read_json("iris.json", lines=True)
iris2

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

## Star Wars API

Le projet SWAPI (*Star Wars API*) est une source de données sur l'univers de Star Wars. L'API fournit plusieurs jeux de données concernant les planètes, les vaisseaux, les véhicules, les personnages, les films et les espèces de la saga venue d'une galaxie très, très lointaine.

1. Utiliser la fonction Pandas `read_json` pour importer les données sur les planètes disponibles au format JSON à l'adresse [https://swapi-node.vercel.app/api/planets](https://swapi-node.vercel.app/api/planets) dans un dataframe. Est-ce que le résultat est facilement exploitable sous cette forme ?

In [ ]:
url_sw = "https://swapi-node.vercel.app/api/planets"

pd.read_json(url_sw)

,count,pages,next,previous,results
0,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.411...
1,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.420...
2,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.421...
3,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.423...
4,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.425...
5,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.427...
6,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.429...
7,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.430...
8,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.432...
9,60,6,/api/planets?page=2,NaN,{'fields': {'edited': '2014-12-20T20:58:18.434...

2. Utiliser la fonction `get` du module `requests` pour récupérer les mêmes données que dans la question précédente et vérifier le code HTTP obtenu.

In [ ]:
r = requests.get(url_sw)

# Vérification du code HTTP - il faut que le status code soit égal à 200
if r.status_code == 200:
    print("Requête réussie, bravo !")
else:
    print(f"Erreur {r.status_code}")

Requête réussie, bravo !

3. Comprendre les éléments de la réponse obtenue à la question précédente. En particulier, combien y a-t-il de planètes dans `results` et à quoi correspond `next` ?

In [35]:
# on regarde le contenu de l'objet json
# count/pages/next : montre des paquets de 6 pages, avec 10 planetes sur chaque page, 
# et l'url partielle des différentes pages
# next : donne adresse de la page d'après (ici 2e page)
planets = r.json()
planets

{'count': 60,
 'pages': 6,
 'next': '/api/planets?page=2',
 'previous': None,
 'results': [{'fields': {'edited': '2014-12-20T20:58:18.411Z',
    'climate': 'arid',
    'surface_water': '1',
    'name': 'Tatooine',
    'diameter': '10465',
    'rotation_period': '23',
    'created': '2014-12-09T13:50:49.641Z',
    'terrain': 'desert',
    'gravity': '1 standard',
    'orbital_period': '304',
    'population': '200000',
    'residents': [],
    'films': [],
    'url': '/api/planets/1'}},
  {'fields': {'edited': '2014-12-20T20:58:18.420Z',
    'climate': 'temperate',
    'surface_water': '40',
    'name': 'Alderaan',
    'diameter': '12500',
    'rotation_period': '24',
    'created': '2014-12-10T11:35:48.479Z',
    'terrain': 'grasslands, mountains',
    'gravity': '1 standard',
    'orbital_period': '364',
    'population': '2000000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/2'}},
  {'fields': {'edited': '2014-12-20T20:58:18.421Z',
    'climate': 'temperate, tropical',
    'surface_water': '8',
    'name': 'Yavin IV',
    'diameter': '10200',
    'rotation_period': '24',
    'created': '2014-12-10T11:37:19.144Z',
    'terrain': 'jungle, rainforests',
    'gravity': '1 standard',
    'orbital_period': '4818',
    'population': '1000',
    'residents': [],
    'films': [],
    'url': '/api/planets/3'}},
  {'fields': {'edited': '2014-12-20T20:58:18.423Z',
    'climate': 'frozen',
    'surface_water': '100',
    'name': 'Hoth',
    'diameter': '7200',
    'rotation_period': '23',
    'created': '2014-12-10T11:39:13.934Z',
    'terrain': 'tundra, ice caves, mountain ranges',
    'gravity': '1.1 standard',
    'orbital_period': '549',
    'population': 'unknown',
    'residents': [],
    'films': [],
    'url': '/api/planets/4'}},
  {'fields': {'edited': '2014-12-20T20:58:18.425Z',
    'climate': 'murky',
    'surface_water': '8',
    'name': 'Dagobah',
    'diameter': '8900',
    'rotation_period': '23',
    'created': '2014-12-10T11:42:22.590Z',
    'terrain': 'swamp, jungles',
    'gravity': 'N/A',
    'orbital_period': '341',
    'population': 'unknown',
    'residents': [],
    'films': [],
    'url': '/api/planets/5'}},
  {'fields': {'edited': '2014-12-20T20:58:18.427Z',
    'climate': 'temperate',
    'surface_water': '0',
    'name': 'Bespin',
    'diameter': '118000',
    'rotation_period': '12',
    'created': '2014-12-10T11:43:55.240Z',
    'terrain': 'gas giant',
    'gravity': '1.5 (surface), 1 standard (Cloud City)',
    'orbital_period': '5110',
    'population': '6000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/6'}},
  {'fields': {'edited': '2014-12-20T20:58:18.429Z',
    'climate': 'temperate',
    'surface_water': '8',
    'name': 'Endor',
    'diameter': '4900',
    'rotation_period': '18',
    'created': '2014-12-10T11:50:29.349Z',
    'terrain': 'forests, mountains, lakes',
    'gravity': '0.85 standard',
    'orbital_period': '402',
    'population': '30000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/7'}},
  {'fields': {'edited': '2014-12-20T20:58:18.430Z',
    'climate': 'temperate',
    'surface_water': '12',
    'name': 'Naboo',
    'diameter': '12120',
    'rotation_period': '26',
    'created': '2014-12-10T11:52:31.066Z',
    'terrain': 'grassy hills, swamps, forests, mountains',
    'gravity': '1 standard',
    'orbital_period': '312',
    'population': '4500000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/8'}},
  {'fields': {'edited': '2014-12-20T20:58:18.432Z',
    'climate': 'temperate',
    'surface_water': 'unknown',
    'name': 'Coruscant',
    'diameter': '12240',
    'rotation_period': '24',
    'created': '2014-12-10T11:54:13.921Z',
    'terrain': 'cityscape, mountains',
    'gravity': '1 standard',
    'orbital_period': '368',
    'population': '1000000000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/9'}},
  {'fields': {'edited': '2014-12-20T20:58:18.434Z',
    'climate': 'temperate',
    'surface_water': '100',
    'name': 'Kamino',
    'diameter': '19720',
    'rotation_period': '27',
    'created': '2014-12-10T12:45:06.577Z',
    'terrain': 'ocean',
    'gravity': '1 standard',
    'orbital_period': '463',
    'population': '1000000000',
    'residents': [],
    'films': [],
    'url': '/api/planets/10'}}]}

In [ ]:
url_base = "https://swapi-node.vercel.app"
url_page = "/api/planets"

url = url_base + url_page

pd.DataFrame(
    [planet["fields"] for planet in planets["results"]]
)

4. Écrire une boucle pour récupérer les informations de toutes les planètes disponibles dans l'API et stocker le résultat dans un dataframe `planets`.

In [ ]:
url_base = "https://swapi-node.vercel.app"
url_page = "/api/planets"

planets_dfs = []
while url_page is not None:
        url = url_base + url_page
        print(f"Téléchargement de {url}")
        r = requests.get(url)
        r.raise_for_status

        planets = r.json()
        planets_dfs.append(
            pd.DataFrame(
                 [planet["fields"] for planet in planets["results"]]
            )
        )

        url_page = planets["next"]

planets_df = pd.concat(planets_dfs, ignore_index=True)
# mettre à jour l'url de la page
# sur cette page, récupérer le dictionnaire fields qui est dans la partie  results en dataframe
# concatener au dataframe précédent

Téléchargement de https://swapi-node.vercel.app/api/planets
Téléchargement de https://swapi-node.vercel.app/api/planets?page=2
Téléchargement de https://swapi-node.vercel.app/api/planets?page=3
Téléchargement de https://swapi-node.vercel.app/api/planets?page=4
Téléchargement de https://swapi-node.vercel.app/api/planets?page=5
Téléchargement de https://swapi-node.vercel.app/api/planets?page=6

In [ ]:
planets_df

5. Exporter le dataframe obtenu à la question précédente dans un fichier `planets.json` au format NDJSON.

In [48]:
planets_df.to_json("planets.json", orient="records", lines=True)