# Notebook 6 : MongoDB

In [ ]:
# Décommenter la ligne suivante pour installer pymongo
# %pip install pymongo

In [1]:
import json

import pandas as pd
import pymongo

client = pymongo.MongoClient(
    # Coller ici la configuration donnée dans Onyxia
    "mongodb://user-jcoutet-ensae:6s3z4yx1falpy9l2lsq4@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017/defaultdb?authSource=defaultdb"
)

db = client.defaultdb

## Planètes de Star Wars

Nous considérons ici les données des planètes de *Star Wars* exportées à la fin du *Notebook 4*. Le fichier `planets.json` est également disponible dans le dossier des jeux de données.

1. Accéder à une collection `planets` et s'assurer qu'elle est vide grâce à la méthode `count_documents`.

In [ ]:
# on crée une collection planets
planets = db["planets"]
planets.drop() # on jette tous les documents de planets
planets.count_documents({})

0

2. Importer les données des planètes dans la collection `planets`.

In [ ]:
# crée dataframe à partir de données
# on le lit avec pandas et fonction to_dict pour convertir en dictionnaire
# insert_many : importe les données dans la collection planets
planets.insert_many(
    pd.read_json("../data/planets.json", lines=True)
    .to_dict(orient="records")
)

# info : correction fait autrement

InsertManyResult([ObjectId('69d8e8f3da85550f2e500f46'), ObjectId('69d8e8f3da85550f2e500f47'), ObjectId('69d8e8f3da85550f2e500f48'), ObjectId('69d8e8f3da85550f2e500f49'), ObjectId('69d8e8f3da85550f2e500f4a'), ObjectId('69d8e8f3da85550f2e500f4b'), ObjectId('69d8e8f3da85550f2e500f4c'), ObjectId('69d8e8f3da85550f2e500f4d'), ObjectId('69d8e8f3da85550f2e500f4e'), ObjectId('69d8e8f3da85550f2e500f4f'), ObjectId('69d8e8f3da85550f2e500f50'), ObjectId('69d8e8f3da85550f2e500f51'), ObjectId('69d8e8f3da85550f2e500f52'), ObjectId('69d8e8f3da85550f2e500f53'), ObjectId('69d8e8f3da85550f2e500f54'), ObjectId('69d8e8f3da85550f2e500f55'), ObjectId('69d8e8f3da85550f2e500f56'), ObjectId('69d8e8f3da85550f2e500f57'), ObjectId('69d8e8f3da85550f2e500f58'), ObjectId('69d8e8f3da85550f2e500f59'), ObjectId('69d8e8f3da85550f2e500f5a'), ObjectId('69d8e8f3da85550f2e500f5b'), ObjectId('69d8e8f3da85550f2e500f5c'), ObjectId('69d8e8f3da85550f2e500f5d'), ObjectId('69d8e8f3da85550f2e500f5e'), ObjectId('69d8e8f3da85550f2e500f5f'), ObjectId('69d8e8f3da85550f2e500f60'), ObjectId('69d8e8f3da85550f2e500f61'), ObjectId('69d8e8f3da85550f2e500f62'), ObjectId('69d8e8f3da85550f2e500f63'), ObjectId('69d8e8f3da85550f2e500f64'), ObjectId('69d8e8f3da85550f2e500f65'), ObjectId('69d8e8f3da85550f2e500f66'), ObjectId('69d8e8f3da85550f2e500f67'), ObjectId('69d8e8f3da85550f2e500f68'), ObjectId('69d8e8f3da85550f2e500f69'), ObjectId('69d8e8f3da85550f2e500f6a'), ObjectId('69d8e8f3da85550f2e500f6b'), ObjectId('69d8e8f3da85550f2e500f6c'), ObjectId('69d8e8f3da85550f2e500f6d'), ObjectId('69d8e8f3da85550f2e500f6e'), ObjectId('69d8e8f3da85550f2e500f6f'), ObjectId('69d8e8f3da85550f2e500f70'), ObjectId('69d8e8f3da85550f2e500f71'), ObjectId('69d8e8f3da85550f2e500f72'), ObjectId('69d8e8f3da85550f2e500f73'), ObjectId('69d8e8f3da85550f2e500f74'), ObjectId('69d8e8f3da85550f2e500f75'), ObjectId('69d8e8f3da85550f2e500f76'), ObjectId('69d8e8f3da85550f2e500f77'), ObjectId('69d8e8f3da85550f2e500f78'), ObjectId('69d8e8f3da85550f2e500f79'), ObjectId('69d8e8f3da85550f2e500f7a'), ObjectId('69d8e8f3da85550f2e500f7b'), ObjectId('69d8e8f3da85550f2e500f7c'), ObjectId('69d8e8f3da85550f2e500f7d'), ObjectId('69d8e8f3da85550f2e500f7e'), ObjectId('69d8e8f3da85550f2e500f7f'), ObjectId('69d8e8f3da85550f2e500f80'), ObjectId('69d8e8f3da85550f2e500f81')], acknowledged=True)

In [39]:
planets.count_documents({})

60

3. Exporter l'ensemble des planètes sans l'identifiant `_id` dans un dataframe à l'aide du résultat de la méthode `find`.

In [43]:
# donne liste des champs
planets.find()[0]

{'_id': ObjectId('69d8e8f3da85550f2e500f46'),
 'edited': '2014-12-20T20:58:18.411Z',
 'climate': 'arid',
 'surface_water': '1',
 'name': 'Tatooine',
 'diameter': '10465',
 'rotation_period': '23',
 'created': '2014-12-09T13:50:49.641Z',
 'terrain': 'desert',
 'gravity': '1 standard',
 'orbital_period': '304',
 'population': '200000',
 'residents': [],
 'films': [],
 'url': '/api/planets/1'}

In [69]:
# crée dataframe
planets_df = pd.DataFrame(planets.find(projection={"_id": False}))
planets_df.head()

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population
0,[arid],1.0,Tatooine,10465.0,23.0,[desert],304.0,2.000000e+05
1,[temperate],40.0,Alderaan,12500.0,24.0,"[grasslands, mountains]",364.0,2.000000e+09
2,"[temperate, tropical]",8.0,Yavin IV,10200.0,24.0,"[jungle, rainforests]",4818.0,1.000000e+03
3,[frozen],100.0,Hoth,7200.0,23.0,"[tundra, ice caves, mountain ranges]",549.0,NaN
4,[murky],8.0,Dagobah,8900.0,23.0,"[swamp, jungles]",341.0,NaN

4. Rechercher les planètes dont la période de rotation est égale à 25. Quel est le problème ? Combien y en a-t-il ?

In [53]:
# attention les données sont en chaînes de caractèrs, il n'y a pas de nombres
planets_df[planets_df["rotation_period"] == "25"]

,edited,climate,surface_water,name,diameter,rotation_period,created,terrain,gravity,orbital_period,population,residents,films,url
17,2014-12-20T20:58:18.449Z,"temperate, moist",unknown,Cato Neimoidia,0,25,2014-12-10T13:46:28.704Z,"mountains, fields, forests, rock arches",1 standard,278,10000000,[],[],/api/planets/18
21,2014-12-20T20:58:18.456Z,temperate,70,Corellia,11000,25,2014-12-10T16:49:12.453Z,"plains, urban, hills, forests",1 standard,329,3000000000,[],[],/api/planets/22
24,2014-12-20T20:58:18.461Z,temperate,unknown,Dantooine,9830,25,2014-12-10T17:23:29.896Z,"oceans, savannas, mountains, grasslands",1 standard,378,1000,[],[],/api/planets/25
28,2014-12-20T20:58:18.468Z,arid,unknown,Trandosha,0,25,2014-12-15T12:53:47.695Z,"mountains, seas, grasslands, deserts",0.62 standard,371,42000000,[],[],/api/planets/29
41,2014-12-20T20:58:18.491Z,temperate,unknown,Haruun Kal,10120,25,2014-12-20T10:12:28.980Z,"toxic cloudsea, plateaus, volcanoes",0.98,383,705300,[],[],/api/planets/42

5. Même question mais en limitant la réponse aux clés `name`, `rotation_period`, `orbital_period` et `diameter`.

6. Trier les planètes du résultat précédent par diamètre décroissant. Quel est le problème ?

7. Vider la collection et importer à nouveau les données mais en faisant les corrections suivantes au préalable (un dataframe intermédiaire pourra être utilisé pour manipuler les données avant leur insertion) :
- convertir les valeurs numériques (gérer les cas `unknown`),
- supprimer les variables `created`, `edited`, `films`, `gravity`, `residents` et `url`.
- transformer les variables `climate` et `terrain` en listes de chaînes de caractères plutôt qu'une longue chaîne séparée par des virgules.

In [ ]:
# transformation de la variable terrain : chaîne de caractères comme suite, on voudrait transformer en liste => split
# ex pour ligne 17 : planets_df["terrain"].iloc[17].split(", ")
# on doit dn cleaner les données avant de les stocker, on revient en arrière

# suppression des variables
df = pd.read_json("../data/planets.json", lines=True)
clean_df = df.drop(columns=["created", "edited", "films", "gravity", "residents", "url"])

# convertir colonnes en numérique
numeric_columns = ["surface_water", "diameter",	"rotation_period",	"orbital_period", "population"]
for column in numeric_columns:
    clean_df[column] = clean_df[column].apply(
        lambda x: float(x) if x != "unknown" else pd.NA
    )

clean_df["climate"] = clean_df["climate"].str.split(", ")
clean_df["terrain"] = clean_df["terrain"].str.split(", ")

In [70]:
# on vide les données non cleanées et on importe les données cleanées
planets.drop()
planets.insert_many(
    clean_df.to_dict(orient="records")
)

# nouveau dataframe cleané
planets_df = pd.DataFrame(planets.find(projection={"_id": False}))
planets_df.head()

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population
0,[arid],1.0,Tatooine,10465.0,23.0,[desert],304.0,2.000000e+05
1,[temperate],40.0,Alderaan,12500.0,24.0,"[grasslands, mountains]",364.0,2.000000e+09
2,"[temperate, tropical]",8.0,Yavin IV,10200.0,24.0,"[jungle, rainforests]",4818.0,1.000000e+03
3,[frozen],100.0,Hoth,7200.0,23.0,"[tundra, ice caves, mountain ranges]",549.0,NaN
4,[murky],8.0,Dagobah,8900.0,23.0,"[swamp, jungles]",341.0,NaN

8. Reprendre la question 6 et vérifier que le résultat est maintenant correct.

In [81]:
# reprendre question 5. Rechercher les planètes dont la période de rotation est égale à 25.
pd.DataFrame(
    planets.find(filter={"rotation_period" : 25}, projection={"_id": False})
)

# question 6. Trier les planètes du résultat précédent par diamètre décroissant
pd.DataFrame(
    planets.find(
        projection={"_id": False},
        sort={"diameter": pymongo.DESCENDING}
    )
)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population
0,[temperate],0.0,Bespin,118000.0,12.0,[gas giant],5110.0,6.000000e+06
1,[temperate],100.0,Kamino,19720.0,27.0,[ocean],463.0,1.000000e+09
2,"[arid, temperate, tropical]",NaN,Malastare,18880.0,26.0,"[swamps, deserts, jungles, mountains]",201.0,2.000000e+09
3,"[tropical, temperate]",80.0,Glee Anselm,15600.0,33.0,"[lakes, islands, swamps, seas]",206.0,5.000000e+08
4,[hot],NaN,Saleucami,14920.0,26.0,"[caves, desert, mountains, volcanoes]",392.0,1.400000e+09
5,"[temperate, artic]",NaN,Vulpter,14900.0,22.0,"[urban, barren]",391.0,4.210000e+08
6,[temperate],10.0,Ord Mantell,14050.0,26.0,"[plains, seas, mesas]",334.0,4.000000e+09
7,"[arid, temperate, tropical]",NaN,Kalee,13850.0,23.0,"[rainforests, cliffs, canyons, seas]",378.0,4.000000e+09
8,[temperate],25.0,Muunilinst,13800.0,28.0,"[plains, forests, hills, mountains]",412.0,5.000000e+09
9,[temperate],40.0,Chandrila,13500.0,20.0,"[plains, forests]",368.0,1.200000e+09
10,[polluted],NaN,Eriadu,13490.0,24.0,[cityscape],360.0,2.200000e+10
11,[temperate],NaN,Dorin,13400.0,22.0,[unknown],409.0,NaN
12,"[temperate, arid, windy]",0.9,Utapau,12900.0,27.0,"[scrublands, savanna, canyons, sinkholes]",351.0,9.500000e+07
13,[superheated],5.0,Sullust,12780.0,20.0,"[mountains, volcanoes, rocky deserts]",263.0,1.850000e+10
14,[tropical],60.0,Kashyyyk,12765.0,26.0,"[jungle, forests, lakes, rivers]",381.0,4.500000e+07
15,[temperate],40.0,Alderaan,12500.0,24.0,"[grasslands, mountains]",364.0,2.000000e+09
16,[temperate],NaN,Coruscant,12240.0,24.0,"[cityscape, mountains]",368.0,1.000000e+12
17,[unknown],NaN,Tund,12190.0,48.0,"[barren, ash]",1770.0,0.000000e+00
18,[temperate],NaN,Nal Hutta,12150.0,87.0,"[urban, oceans, swamps, bogs]",413.0,7.000000e+09
19,[temperate],12.0,Naboo,12120.0,26.0,"[grassy hills, swamps, forests, mountains]",312.0,4.500000e+09
20,"[temperate, arid]",5.0,Geonosis,11370.0,30.0,"[rock, desert, mountain, barren]",256.0,1.000000e+11
21,[temperate],100.0,Mon Cala,11030.0,21.0,"[oceans, reefs, islands]",398.0,2.700000e+10
22,[temperate],70.0,Corellia,11000.0,25.0,"[plains, urban, hills, forests]",329.0,3.000000e+09
23,"[temperate, arid, subartic]",5.0,Ryloth,10600.0,30.0,"[mountains, valleys, deserts, tundra]",305.0,1.500000e+09
24,[temperate],NaN,Dathomir,10480.0,24.0,"[forests, deserts, savannas]",491.0,5.200000e+03
25,[arid],1.0,Tatooine,10465.0,23.0,[desert],304.0,2.000000e+05
26,"[temperate, tropical]",8.0,Yavin IV,10200.0,24.0,"[jungle, rainforests]",4818.0,1.000000e+03
27,[temperate],NaN,Haruun Kal,10120.0,25.0,"[toxic cloudsea, plateaus, volcanoes]",383.0,7.053000e+05
28,[frigid],NaN,Mygeeto,10088.0,12.0,"[glaciers, mountains, ice canyons]",167.0,1.900000e+07
29,[temperate],NaN,Dantooine,9830.0,25.0,"[oceans, savannas, mountains, grasslands]",378.0,1.000000e+03
30,"[hot, humid]",NaN,Felucia,9100.0,34.0,[fungus forests],231.0,8.500000e+06
31,[murky],8.0,Dagobah,8900.0,23.0,"[swamp, jungles]",341.0,NaN
32,[temperate],NaN,Toydaria,7900.0,21.0,"[swamps, lakes]",184.0,1.100000e+07
33,[hot],60.0,Rodia,7549.0,29.0,"[jungles, oceans, urban, swamps]",305.0,1.300000e+09
34,[frozen],100.0,Hoth,7200.0,23.0,"[tundra, ice caves, mountain ranges]",549.0,NaN
35,[temperate],98.0,Bestine IV,6400.0,26.0,"[rocky islands, oceans]",680.0,6.200000e+07
36,[temperate],8.0,Endor,4900.0,18.0,"[forests, mountains, lakes]",402.0,3.000000e+07
37,[hot],0.0,Mustafar,4200.0,36.0,"[volcanoes, lava rivers, mountains, caves]",412.0,2.000000e+04
38,[artificial temperate ],0.0,Polis Massa,0.0,24.0,[airless asteroid],590.0,1.000000e+06
39,"[temperate, moist]",NaN,Cato Neimoidia,0.0,25.0,"[mountains, fields, forests, rock arches]",278.0,1.000000e+07
40,[temperate],NaN,Stewjon,0.0,NaN,[grass],NaN,NaN
41,[unknown],NaN,unknown,0.0,0.0,[unknown],0.0,NaN
42,[arid],NaN,Trandosha,0.0,25.0,"[mountains, seas, grasslands, deserts]",371.0,4.200000e+07
43,[arid],NaN,Socorro,0.0,20.0,"[deserts, mountains]",326.0,3.000000e+08
44,[unknown],NaN,Aleen Minor,NaN,NaN,[unknown],NaN,NaN
45,[unknown],NaN,Troiken,NaN,NaN,"[desert, tundra, rainforests, mountains]",NaN,NaN
46,[temperate],20.0,Cerea,NaN,27.0,[verdant],386.0,4.500000e+08
47,[unknown],NaN,Iridonia,NaN,29.0,"[rocky canyons, acid pools]",413.0,NaN
48,[unknown],NaN,Tholoth,NaN,NaN,[unknown],NaN,NaN
49,"[arid, rocky, windy]",NaN,Iktotch,NaN,22.0,[rocky],481.0,NaN
50,[unknown],NaN,Quermia,NaN,NaN,[unknown],NaN,NaN
51,[temperate],NaN,Champala,NaN,27.0,"[oceans, rainforests, plateaus]",318.0,3.500000e+09
52,[unknown],NaN,Mirial,NaN,NaN,[deserts],NaN,NaN
53,[unknown],NaN,Serenno,NaN,NaN,"[rainforests, rivers, mountains]",NaN,NaN
54,[unknown],NaN,Concord Dawn,NaN,NaN,"[jungles, forests, deserts]",NaN,NaN
55,[unknown],NaN,Zolan,NaN,NaN,[unknown],NaN,NaN
56,[frigid],100.0,Ojom,NaN,NaN,"[oceans, glaciers]",NaN,5.000000e+08
57,[temperate],NaN,Skako,NaN,27.0,"[urban, vines]",384.0,5.000000e+11
58,[temperate],NaN,Shili,NaN,NaN,"[cities, savannahs, seas, plains]",NaN,NaN
59,[unknown],NaN,Umbara,NaN,NaN,[unknown],NaN,NaN

9. Extraire les planètes dont le nom commence par `T`.

In [83]:
pd.DataFrame(
    planets.find(
        filter={"name" : {"$regex" : "^T"}},
        projection={"_id": False}
    )
)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population
0,[arid],1.0,Tatooine,10465.0,23.0,[desert],304.0,200000.0
1,[arid],NaN,Trandosha,0.0,25.0,"[mountains, seas, grasslands, deserts]",371.0,42000000.0
2,[temperate],NaN,Toydaria,7900.0,21.0,"[swamps, lakes]",184.0,11000000.0
3,[unknown],NaN,Troiken,NaN,NaN,"[desert, tundra, rainforests, mountains]",NaN,NaN
4,[unknown],NaN,Tund,12190.0,48.0,"[barren, ash]",1770.0,0.0
5,[unknown],NaN,Tholoth,NaN,NaN,[unknown],NaN,NaN

10. Extraire les planètes dont le diamètre est strictement supérieur à 10000 et où se trouvent des montagnes.

In [87]:
pd.DataFrame(
    planets.find(
        filter={
            "$and" : [
            {"diameter" : {"$gt" : 10000}},
            {"terrain" : {"$in" : ["mountains"] }}
            ]
        },
        projection={"_id": False}
    )
)

,climate,surface_water,name,diameter,rotation_period,terrain,orbital_period,population
0,[temperate],40.0,Alderaan,12500.0,24.0,"[grasslands, mountains]",364.0,2.000000e+09
1,[temperate],12.0,Naboo,12120.0,26.0,"[grassy hills, swamps, forests, mountains]",312.0,4.500000e+09
2,[temperate],NaN,Coruscant,12240.0,24.0,"[cityscape, mountains]",368.0,1.000000e+12
3,[frigid],NaN,Mygeeto,10088.0,12.0,"[glaciers, mountains, ice canyons]",167.0,1.900000e+07
4,[hot],NaN,Saleucami,14920.0,26.0,"[caves, desert, mountains, volcanoes]",392.0,1.400000e+09
5,[superheated],5.0,Sullust,12780.0,20.0,"[mountains, volcanoes, rocky deserts]",263.0,1.850000e+10
6,"[arid, temperate, tropical]",NaN,Malastare,18880.0,26.0,"[swamps, deserts, jungles, mountains]",201.0,2.000000e+09
7,"[temperate, arid, subartic]",5.0,Ryloth,10600.0,30.0,"[mountains, valleys, deserts, tundra]",305.0,1.500000e+09
8,[temperate],25.0,Muunilinst,13800.0,28.0,"[plains, forests, hills, mountains]",412.0,5.000000e+09

11. Rechercher puis supprimer la planète dont le nom est `unknown`.

In [93]:
pd.DataFrame(
    planets.find(
        filter={"name" : "unknown"},
        projection={"_id": False})
)

planets.delete_one({"name" : "unknown"})

pd.DataFrame(
    planets.find(
        filter={"name" : "unknown"},
        projection={"_id": False})
)

Empty DataFrame
Columns: []
Index: []

12. Mettre en œuvre un pipeline d'agrégation qui calcule le nombre de planètes dans la collection. Verifier le résultat avec la méthode `count_documents`.

In [ ]:
pd.DataFrame(
    planets.aggregate([
         {"$group": {"_id": None, "count": {"$sum": 1}}}
    ]
    )
)

    _id  count
0  None     59

13. Mettre en œuvre un pipeline d'agrégation pour calculer le diamètre moyen et la somme des populations des planètes contenant des glaciers.

In [97]:
pd.DataFrame(
    planets.aggregate([
        {"$match" : {"terrain": {"$in" : ["glaciers"]}}},
        {"$group": {
            "_id": None,
            "diametre_moyen": {"$avg": "$diameter"},
            "pop_total" : {"$sum" : "$population"}}}
         ]
    )
)

    _id  diametre_moyen    pop_total
0  None         10088.0  519000000.0